### ISSUE TITLE
设备页面怎么恢复？

### ISSUE THREAD

**Issue by yrsmile** [linkease/ddnsto#189]
我在控制台把设备删除后，现在无法添加新设备，设备页面变成这样，怎么办，谢谢

![微信图片_20210705093500](https://user-images.githubusercontent.com/86901412/124406600-637ccc00-dd74-11eb-96f0-5d20e99a4ca2.png)

**Comment by yrsmile** [comment]
找到原因了，是NAS虚拟交换机网关设置的原因，导致内网服务无法正常运行

**Comment by 545433836** [comment]
我也是同样问题，请问后面改怎么样操作？

**Comment by yrsmile** [comment]
是NAS的虚拟网卡设置问题，和DDNSTO没关系，我重置了NAS网络设定，就解决了。
希望以上解答能帮到你

----- 原始邮件 -----
发件人：545433836 ***@***.***>
收件人：linkease/ddnsto ***@***.***>
抄送人：yrsmile ***@***.***>,  State change ***@***.***>
主题：Re:_[linkease/ddnsto]_设备页面怎么恢复？_(#189)
日期：2022年03月02日 22点22分



我也是同样问题，请问后面改怎么样操作？



—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 545433836** [comment]
怎么样重制nas设置？





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yrsmile ***@***.***&gt;
发送时间: 2022年3月4日 15:38
收件人: linkease/ddnsto ***@***.***&gt;
抄送: 545433836 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [linkease/ddnsto] 设备页面怎么恢复？ (#189)





 是NAS的虚拟网卡设置问题，和DDNSTO没关系，我重置了NAS网络设定，就解决了。
 希望以上解答能帮到你
 
 ----- 原始邮件 -----
 发件人：545433836 ***@***.***&gt;
 收件人：linkease/ddnsto ***@***.***&gt;
 抄送人：yrsmile ***@***.***&gt;,  State change ***@***.***&gt;
 主题：Re:_[linkease/ddnsto]_设备页面怎么恢复？_(#189)
 日期：2022年03月02日 22点22分
 
 
 
 我也是同样问题，请问后面改怎么样操作？ 
 
 
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 
 
 You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
